apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-influxdb2-datasource
  labels:
     grafana_datasource: "1"
data:
  influxdb2-datasource.yaml: |-
      # config file version
      {
        "apiVersion": 1 ,
        "datasources": [
          {

            "name" : "influxdb2",
            "type" : "influxdb",
            "access" : "proxy",
            "orgId": 1,
            "version" : 1,
            "editable": true,
        
            "url": {{ if .Values.global }} "http://{{ .Values.global.influxdb.host }}:{{ .Values.global.influxdb.port }}" {{ else }}"http://{{ .Values.datasources.influxdbV2.url }}"{{ end }} ,
            "password": "pwd",
            "user": "admin",
            "jsonData": {
              "defaultBucket": {{ if .Values.global }} {{ .Values.global.systemName | quote  }} {{ else }} {{ .Values.datasources.influxdbV2.defaultBucket | quote }} {{ end }} ,
              "httpMode": "GET",
              "organization":  {{ .Values.datasources.influxdbV2.defaultOrg }} ,
              "version": "Flux" }
            
            
      
          }
      ]
      }