apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-testdatadb
  labels:
     grafana_datasource: "1"
data:
  testdata-datasource.yaml: |-
      # config file version
      {
        "apiVersion": 1 ,
        "datasources": [
          {

            "name" : "TestData DB",
            "type" : "testdata",
            
          }
      ]
      }
