apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telegraf.fullname" . }}
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
data:
  telegraf.conf: |+
    {{- $tplVersion := include "detect.version" . }}
    {{ template "global_tags" .Values.config.global_tags }}
    {{ template "agent" .Values.config.agent }}
    {{ template "processors" (list $tplVersion .Values.config.processors) }}
    {{ template "aggregators" (list $tplVersion .Values.config.aggregators) }}
    {{ template "outputs" (list $tplVersion .Values.config.outputs) }}
    [[inputs.mqtt_consumer]]
      servers = {{- if .Values.global }}["tcp://{{ .Values.global.mosquitto.host }}:{{ .Values.global.mosquitto.port }}"]{{- else }}["tcp://{{ .Values.inputs.mosquitto.host }}:{{ .Values.inputs.mosquitto.port }}"]{{- end }}
      topics = {{- if .Values.global }}["{{.Values.global.telegraf.topics}}"]{{- else }}["{{.Values.inputs.mosquitto.topics}}"]{{- end}}
      {{- if .Values.inputs.mosquitto.dataFormat}}
      data_format = {{- if .Values.global }}"{{.Values.global.telegraf.dataFormat}}"{{- else }}"{{.Values.inputs.mosquitto.dataFormat}}"{{- end}}
      {{- end }}
      {{- if .Values.inputs.mosquitto.tagKeys}}
      tag_keys = {{if .Values.global }} [{{range  $index,$element :=  .Values.global.telegraf.tagKeys }}{{if $index }},{{end}} {{  $element | quote }}  {{ end }}]
      {{ else }} [{{range  $index,$element :=  .Values.inputs.mosquitto.tagKeys }}{{if $index }},{{end}} {{  $element | quote }}  {{ end }}]{{ end }}
      {{- end }}
      {{- if .Values.inputs.mosquitto.jsonFields}}
      json_string_fields = {{if .Values.global }} [{{range  $index,$element :=  .Values.global.telegraf.jsonFields }}{{if $index }},{{end}} {{  $element | quote }}  {{ end }}]
      {{ else }} [{{range  $index,$element :=  .Values.inputs.mosquitto.jsonFields }}{{if $index }},{{end}} {{  $element | quote }}  {{ end }}]{{ end }}
      {{- end }}
    [[outputs.influxdb_v2]]
      urls ={{if .Values.global }}["http://{{ .Values.global.influxdb.host }}:{{ .Values.global.influxdb.port }}"]{{- else }}["http://{{ .Values.outputs.influxdb.host }}:{{ .Values.outputs.influxdb.port }}"]{{- end}}
      bucket = {{if .Values.global }} {{ .Values.global.systemName | quote }}{{- else }}{{ .Values.outputs.influxdb.bucket | quote }}{{- end}}
      organization = {{ .Values.outputs.influxdb.organization  | quote }}
    {{- if .Values.metrics.health.enabled }}
    [[outputs.health]]
      service_address = "{{ .Values.metrics.health.service_address }}"
      namepass = ["internal_write"]
      [[outputs.health.compares]]
        field = "buffer_size"
        lt = {{ .Values.metrics.health.threshold | int64 }}.0
      [[outputs.health.contains]]
        field = "buffer_size"
    {{- end }}
    {{ template "inputs" (list $tplVersion .Values.config.inputs) }}
    {{- if .Values.metrics.internal.enabled }}
    [[inputs.internal]]
      collect_memstats = {{ or .Values.metrics.internal.collect_memstats (.Values.metrics.collect_memstats | default false) }}
    {{- end }}