{
 "title": "CAT dash",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Velocità Linea TG3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "metri al minuto",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Velocita_(metri_minuto)_Linea" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Velocità Cavalletto 1",
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cavalletto 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Velocita_Cavalletto_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Velocità Cavalletto 2",
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cavalletto 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Velocita_Cavalletto_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Velocità Pompa",
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Pompa",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opcua_metrics",
     "select": [
      [
       {
        "params": [
         "Pompa_ingranaggi_velocita_attuale"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Velocità",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "Cavalletto 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Velocita_Cavalletto_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cavalletto 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Velocita_Cavalletto_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Metri/minuto",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Velocita_(metri_minuto)_Linea" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Traino 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       {
        "params": [
         "Velocita_traino_1_(ingresso_master)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Traino 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       {
        "params": [
         "Velocita_traino_2_(uscita_slave)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cavalletto 1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "25",
     "measurement": "S7300",
     "query": "SELECT \"Cavalletto_1_(allarme)\" FROM \"S7300\" WHERE $timeFilter LIMIT 25",
     "select": [
      [
       { "params": [ "Cavalletto_1_(allarme)" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cavalletto 2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "25",
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Cavalletto_2_(allarme)" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pompa Riciclo",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "25",
     "measurement": "S7300",
     "query": "SELECT \"Traino_1_(allarme)\" FROM \"S7300\" WHERE $timeFilter LIMIT 25",
     "select": [
      [
       { "params": [ "Pompa_riciclo_(allarme)" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Velocità Traino 1",
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Traino 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       {
        "params": [
         "Velocita_traino_1_(ingresso_master)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Velocità Traino 2",
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Traino 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       {
        "params": [
         "Velocita_traino_2_(uscita_slave)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Velocità Estrusore",
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Estrusore",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opcua_metrics",
     "select": [
      [
       { "params": [ "Estrusore_velocita" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Assorbimento Motori",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "Cavalletto 1",
     "measurement": "S7300",
     "query": "SELECT \"SpZona2\" FROM \"S7300\" ",
     "select": [
      [
       {
        "params": [
         "Assorbimento_motore_cavalletto_1"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Cavalletto 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       {
        "params": [
         "Assorbimento_motore_cavalletto_2"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Traino 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Assorbimento_motore_traino_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Traino 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Assorbimento_motore_traino_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traino Mandata",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "25",
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Traino_Mandata_(allarme)" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traino Tirata",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Traino Tirata",
     "limit": "25",
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Traino_Tirata_(allarme)" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pompa Distaccante",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "25",
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Pompa_distaccante_(allarme)" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stato Marcia",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "Cavalletto 1",
     "measurement": "S7300",
     "select": [
      [
       {
        "params": [
         "Cavalletto_1_(stato_marcia_arresto)"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Cavalletto 2",
     "measurement": "S7300",
     "select": [
      [
       {
        "params": [
         "Cavalletto_2_(stato_marcia_arresto)"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Chiller",
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Chiller_(stato_marcia_arresto)" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Pompa Distaccante",
     "measurement": "S7300",
     "select": [
      [
       {
        "params": [
         "Pompa_distaccante_(stato_marcia_arresto)"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Pompa Riciclo",
     "measurement": "S7300",
     "select": [
      [
       {
        "params": [
         "Pompa_riciclo_(stato_marcia_arresto)"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Traino Mandata",
     "measurement": "S7300",
     "select": [
      [
       {
        "params": [
         "Traino_Mandata_(stato_marcia_arresto)"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Traino Tirata",
     "measurement": "S7300",
     "select": [
      [
       {
        "params": [
         "Traino_Tirata_(stato_marcia_arresto)"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature zone",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "Testa - zona1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opcua_metrics",
     "select": [
      [
       {
        "params": [
         "Temperatura_zona_1_(testa)_attuale"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cilindro - zona3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opcua_metrics",
     "select": [
      [
       {
        "params": [
         "Temperatura_zona_3_(cilindro_1)_attuale"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Matrice - zona4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opcua_metrics",
     "select": [
      [
       {
        "params": [
         "Temperatura_zona_4_(matrice_2)_attuale"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cilindro3 - zona5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opcua_metrics",
     "select": [
      [
       {
        "params": [
         "Temperatura_zona_5_(cilindro_3)_attuale"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Vite - zona6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opcua_metrics",
     "select": [
      [
       {
        "params": [
         "Temperatura_zona_6_(vite)_attuale"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Valore di Correzione Sikora Zumbach",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "correzione",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "S7300",
     "select": [
      [
       {
        "params": [
         "Valore_correzione_sikora_zumbach"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scelta Sikora Zumbach",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "S7300",
     "select": [
      [
       { "params": [ "Scelta_Sikora_zumbach" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}