{
 "title": "Forecast Display",
 "description": "Display actual and forecasted confidence interval for metrics from influxdb",
 "time": { "from": "now-30d", "to": "now+4d" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "city", "query": "show databases" },
   { "name": "metric", "query": "show measurements on $city" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 1, "y": 0 },
   "options": {
    "content": "![Image](https://gitea.cloud.vm/HPE/images/raw/branch/main/advanced_edge_forecasting.png)"
   }
  },
  {
   "title": "Last Forecast Model Used for $city in Edge",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select model_name, value from $city..${metric}_fc order by desc limit 1\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM $city..${metric}_rd"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM $city..${metric}_fc"
    }
   ]
  },
  {
   "title": "Last point of $metric Current",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM $city..${metric}_rd"
    }
   ]
  },
  {
   "title": "Last point of $metric Forecast",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM $city..${metric}_fc"
    }
   ]
  },
  {
   "title": "Trend of $metric",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 6 },
   "repeat": "city",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "rd",
     "query": "SELECT \"value\" FROM $city..${metric}_rd"
    },
    {
     "alias": "fc",
     "query": "SELECT \"value\" FROM $city..${metric}_fc"
    },
    {
     "alias": "high",
     "query": "SELECT \"CI_high\" FROM $city..${metric}_fc"
    },
    {
     "alias": "low",
     "query": "SELECT \"CI_low\" FROM $city..${metric}_fc"
    },
    {
     "query": "SELECT \"model_name\" FROM $city..${metric}_fc"
    }
   ]
  }
 ]
}