apiVersion: v1
kind: Service
metadata:
  name: {{ if .Values.global }} {{ .Values.global.prometheus.host | quote }} {{ else }} {{ include "prometheus-helm.fullname" . }} {{ end}} 
  labels:
    {{- include "prometheus-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    targetPort: 9090
    protocol: TCP
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "prometheus-helm.selectorLabels" . | nindent 4 }}













