# Default values for toolbox-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "toolbox"

####___________________________________Enablers Values______________________________________________________________________
telegrafToMap:
  enabled: false
telegrafToCloud:
  enabled: true
telegrafOpcua:
  enabled: true
telegrafS7comm:
  enabled: true
mosquitto:
  enabled: true
influxdb:
  enabled: false
grafana: 
  enabled: true
prometheus:
  enabled: true
datagen: 
  enabled: false
nfsEnabled: false






#_______________________________________Grafana values_______________________________________________________________________
grafana-helm:
  service:
    type: "NodePort"
    nodePort: "30085"
  customized:
    dashboards:
      mobileApp:
        enabled: "false"
      monitoring:
        enabled: "true"
      map: 
        enabled: "false"
      forecastDisplay:
        enabled: "false"
      labDisplay:
        enabled: "false"
      caterpillar:
        enabled: "true"
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: traefik
      # kubernetes.io/tls-acme: "true"
    hosts: ["grafana.cat.cloud"]
    path: /
    pathType: Prefix
    tls: 
      - hosts:
        - grafana.cat.cloud
        secretName: grafana-tls

  datasources:
    influxdbV1:
        enabled: "true"
        url: "influxdb:8086"
        defaultDatabase: "Cat"
    influxdbV2:
        enabled: "true"
        url: "influxdb:8086"
        defaultBucket: "Cat"
        defaultOrg: "HPE"
    testdataDB:
        enabled: "true"
        
    prometheus:
        enabled: "true"
        url: "prometheus:8080"








#____________________________________________Mosquitto________________________________________________________________________-
mosquitto-helm:
  fullnameOverride: "mosquitto"
  service: 
    type : "NodePort"
    nodePort: 30183
  

# Prometheus Values
prometheus-helm: 
  fullnameOverride: "prometheus" 
  config:
    cluster : "https://192.192.192.2:6443"
  service: 
      type: "NodePort"
      nodePort: 30011
  



#___________________________________________________________________TelegraftoCloud Values_________________________________________________________________

telegraftocloud-helm:
    inputs:
      mosquitto:
        host: "mosquitto"
        port: 1883
        topics: "#"
    outputs:
      mosquittoCloud:
        host: "192.192.192.2"
        port:  30183
        topicPrefix : "opcua_metrics"
#__________________TelegraftoMap Values_________________________________________________________________________--_
telegraftomap-helm:
  inputs:
    mosquitto:
      host: "mosquitto"
      port: 1883
      topics: "#"
  outputs:
    influxdb:  
      host: "influxdb"
      port: 8086
      bucket: "Cat"
      organization : "HPE"
nfs-subdir-external-provisioner :
  nfs:
    server: "134.44.28.124"
    path: "share/edge-svil"
  storageClass:
    name: "nfs"

#________________________________________Influxdb Values______________________________________________________________
influxdb-helm:
  initScripts:
    enabled: true
    defaultDatabase: "Cat"
  env:
  - {name: "INFLUXDB_HTTP_FLUX_ENABLED" , value: "true"}
  - {name: "INFLUXDB_ADMIN_ENABLED" , value : "true"}
  - {name : "INFLUXDB_ADMIN_USER" , value : "admin"}
  - {name : "INFLUXDB_ADMIN_PASSWORD" , value : "pwd"}
  - {name : "INFLUXDB_USER" , value : "user"}
  - {name : "INFLUXDB_USER_PASSWORD" , value : "pwd"}
  - {name : "DOCKER_INFLUXDB_INIT_BUCKET" , value : "Cat"}
  - {name : "DOCKER_INFLUXDB_INIT_ORG" , value : "HPE"}          
  
#__________________________________________Telegraf_S7Comm____________________________________________________________________
telegrafs7comm-helm:
  metrics:
    s7comm:
      enabled: true 
      name: "S7300"
      plc:
        ip: "192.168.1.1"
        rack: "0"
        slot: "2"
      connectTimeout: "10s"
      requestTimeout: "2s"
      nodes: ['{name="Ballerino_(monitoraggio)", address="DB98.DBD100", type="real"},{name="Cavalletto_1_(stato_marcia_arresto)", address="DB40.DBX1.3", type="bool"},{name="Cavalletto_1_(allarme)", address="DB100.DBX91.3", type="bool"},{name="Cavalletto_2_(stato_marcia_arresto)", address="DB50.DBX1.3", type="bool"},{name="Cavalletto_2_(allarme)", address="DB100.DBX135.3", type="bool"},{name="Traino_Mandata_(stato_marcia_arresto)", address="DB20.DBX1.3", type="bool"},{name="Traino_Mandata_(allarme)", address="DB100.DBX3.3", type="bool"},{name="Traino_Tirata_(stato_marcia_arresto)", address="DB30.DBX1.3", type="bool"},{name="Traino_Tirata_(allarme)", address="DB100.DBX47.3", type="bool"},{name="Protezioni_traino_Mandata_(monitoraggio)", address="DB5.DBX8.7", type="bool"},{name="Protezioni_traino_Mandata_(allarme)", address="DB90.DBX20.7", type="bool"},{name="Protezioni_traino_Tirata_(monitoraggio)", address="DB5.DBX9.0", type="bool"},{name="Protezioni_traino_Tirata_(allarme)", address="DB90.DBX21.0", type="bool"},{name="Pompa_riciclo_(stato_marcia_arresto)", address="DB98.DBX64.6", type="bool"},{name="Pompa_riciclo_(allarme)", address="DB98.DBX123.7", type="bool"},{name="Pompa_distaccante_(stato_marcia_arresto)", address="DB98.DBX64.3", type="bool"},{name="Pompa_distaccante_(allarme)", address="DB98.DBX124.0", type="bool"},{name="Chiller_(stato_marcia_arresto)", address="DB98.DBX64.2", type="bool"},{name="Velocita_traino_1_(ingresso_master)", address="DB98.DBD68", type="real"},{name="Velocita_traino_2_(uscita_slave)", address="DB98.DBD72", type="real"},{name="Traini_tiro_velocita", address="DB98.DBX0.4", type="bool"},{name="Traini_Correzione_tiro_2", address="DB98.DBD8", type="real"},{name="Velocita_Cavalletto_1", address="DB98.DBW108", type="int"},{name="Velocita_Cavalletto_2", address="DB98.DBW110", type="int"},{name="Cavalletti_1_selezionato", address="DB98.DBX0.5", type="bool"},{name="Cavalletti_2_selezionato", address="DB98.DBX0.7", type="bool"},{name="Scelta_Sikora_zumbach", address="DB98.DBX40.0", type="bool"},{name="Valore_correzione_sikora_zumbach", address="DB95.DBD4", type="real"},{name="Assorbimento_motore_traino_1", address="DB98.DBD84", type="real"},{name="Assorbimento_motore_traino_2", address="DB98.DBD88", type="real"},{name="Assorbimento_motore_cavalletto_1", address="DB98.DBW112", type="int"},{name="Assorbimento_motore_cavalletto_2", address="DB98.DBW114", type="int"},{name="Velocita_(metri_minuto)_Linea", address="DB98.DBD72", type="real"},{name="Metri_prodotti", address="DB18.DBD44", type="real"}']

#____________________________________________Telegraf_Opcua________________________________________________________________-
telegrafopcua-helm:
  metrics:
    opcua:
      enabled: true 
      endpoint: "opc.tcp://90.90.90.12:4840"
      securityPolicy: "None"
      groupname: "opcua_metrics" 
      namespace: "2"
      identifierType: "s"
      nodes : ['{name="Assorbimento_motore_pompa_ingranaggi",identifier="\"DB11 from line\".\"GP_Current\""},{name="Assorbimento_motore_estrusore",identifier="\"DB11 from line\".\"Extruder_Current\""},{name="Temperatura_zona_1_(testa)_setpoint",identifier="\"DB10 to line\".\"Temp_Zone_1\""},{name="Temperatura_zona_2_(pompa)_setpoint",identifier="\"DB10 to line\".\"Temp_Zone_2\""},{name="Temperatura_zona_3_(cilindro_1)_setpoint",identifier="\"DB10 to line\".\"Temp_Zone_3\""},
                {name="Temperatura_zona_4_(matrice_2)_setpoint",identifier="\"DB10 to line\".\"Temp_Zone_4\""},
                {name="Temperatura_zona_5_(cilindro_3)_setpoint",identifier="\"DB10 to line\".\"Temp_Zone_5\""},
                {name="Temperatura_zona_6_(vite)_setpoint",identifier="\"DB10 to line\".\"Temp_Zone_6\""},
                {name="Temperatura_zona_1_(testa)_attuale",identifier="\"DB11 from line\".\"Temp_Zone_1\""},
                {name="Temperatura_zona_2_(pompa)_attuale",identifier="\"DB11 from line\".\"Temp_Zone_2\""},
                {name="Temperatura_zona_3_(cilindro_1)_attuale",identifier="\"DB11 from line\".\"Temp_Zone_3\""},
                {name="Temperatura_zona_4_(matrice_2)_attuale",identifier="\"DB11 from line\".\"Temp_Zone_4\""},
                {name="Temperatura_zona_5_(cilindro_3)_attuale",identifier="\"DB11 from line\".\"Temp_Zone_5\""},
                {name="Temperatura_zona_6_(vite)_attuale",identifier="\"DB11 from line\".\"Temp_Zone_6\""},
                {name="Temperatura_uscita_estrusore",identifier="\"DB11 from line\".\"Tmp_Mat_Z_1\""},
                {name="Temperatura_uscita_pompa",identifier="\"DB11 from line\".\"Tmp_Mat_Z_2\""},
                {name="Pompa_ingranaggi_velocita_setpoint",identifier="\"DB10 to line\".\"GP_Speed\""},
                {name="Pompa_ingranaggi_velocita_attuale",identifier="\"DB11 from line\".\"GP_Speed\""},
                {name="Pompa_ingranaggi_pressione_in_setpoint",identifier="\"DB10 to line\".\"Press_Mat_z_1\""},
                {name="Pompa_ingranaggi_pressione_in_attuale",identifier="\"DB11 from line\".\"Press_Mat_z_1\""},
                {name="Pompa_ingranaggi_pressione_out_setpoint",identifier="\"DB10 to line\".\"Press_Mat_z_2\""},
                {name="Pompa_ingranaggi_pressione_out_attuale",identifier="\"DB11 from line\".\"Press_Mat_z_2\""},
                {name="Estrusore_velocita",identifier="\"DB11 from line\".\"Extruder_Speed\""}']
